services:
  redis:
    image: redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - mode: ingress
        target: 6379
        published: 6379
        protocol: tcp

  backend:
    build: .
    command: >
      sh -c "python manage.py makemigrations & python manage.py migrate & python manage.py collectstatic --noinput & gunicorn core.wsgi --bind 0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - type: bind
        source: ./core
        target: /app
        bind:
          create_host_path: true
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - redis
    environment:
      SECRET_KEY: django-insecure-q7r1r^3_#xp2sp+p=tyn=$s=7!s-i3v%q902b9h@ha64&gk8u&
      DEBUG: False

  worker:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - type: bind
        source: ./core
        target: /app
        bind:
          create_host_path: true
    depends_on:
      - redis
      - backend

  nginx:
    image: nginx
    ports:
      - mode: ingress
        target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./default.conf
        target: /etc/nginx/conf.d/default.conf
        bind:
          create_host_path: true
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
     - redis
     - backend

volumes:
  static_volume:
  media_volume:
